version: '2'
services:
  proxy:
    image: nginx
    container_name: proxy
    ports:
    - "80:80"
    - "443:443"
    - "3306:3306"
    volumes:
    - ./nginx/ssl:/etc/nginx/ssl
    - ./nginx/conf.d:/etc/nginx/conf.d
  api:
    image: magestore/python-api
    container_name: api
    expose:
    - 80
    volumes:
    - ./:/omnisys
    - ./api:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
    - "8080:80"
    environment:
    - PMA_PORT=3306
    - PMA_HOSTS=basic-m2,starter-m2,grow-m2,starter-m2-copy,starter-m2-copy2,grow-m2-copy,grow-m2-copy2,template-m2-copy,grow-m2-from-template
  basic-m2:
    image: magestore/omnichannel_m2
    container_name: basic-m2
    expose:
    - 80
    - 443
    volumes:
    - ./basic-m2/data/www:/var/www/html
    - ./basic-m2/data/mysql:/var/lib/mysql
    - ./basic-m2/config/apache2:/etc/apache2
  grow-m2:
    image: magestore/omnichannel_m2
    ports:
    - '222:22'
    expose:
    - '80'
    - '443'
    volumes:
    - ./grow-m2/data/www:/var/www/html
    - ./grow-m2/data/mysql:/var/lib/mysql
    - ./grow-m2/config/apache2:/etc/apache2
    container_name: grow-m2
    restart: always
  starter-m2:
    image: magestore/omnichannel_m2
    ports:
    - '221:22'
    expose:
    - '80'
    - '443'
    volumes:
    - ./starter-m2/data/www:/var/www/html
    - ./starter-m2/data/mysql:/var/lib/mysql
    - ./starter-m2/config/apache2:/etc/apache2
    container_name: starter-m2
    restart: always
  starter-m2-copy:
    image: magestore/omnichannel_m2
    expose:
    - '80'
    - '443'
    volumes:
    - ./starter-m2-copy/data/www:/var/www/html
    - ./starter-m2-copy/data/mysql:/var/lib/mysql
    - ./starter-m2-copy/config/apache2:/etc/apache2
    container_name: starter-m2-copy
  starter-m2-copy2:
    image: magestore/omnichannel_m2
    expose:
    - '80'
    - '443'
    volumes:
    - ./starter-m2-copy2/data/www:/var/www/html
    - ./starter-m2-copy2/data/mysql:/var/lib/mysql
    - ./starter-m2-copy2/config/apache2:/etc/apache2
    container_name: starter-m2-copy2
  grow-m2-copy:
    image: magestore/omnichannel_m2
    expose:
    - '80'
    - '443'
    volumes:
    - ./grow-m2-copy/data/www:/var/www/html
    - ./grow-m2-copy/data/mysql:/var/lib/mysql
    - ./grow-m2-copy/config/apache2:/etc/apache2
    container_name: grow-m2-copy
  grow-m2-copy2:
    image: magestore/omnichannel_m2
    expose:
    - '80'
    - '443'
    volumes:
    - ./grow-m2-copy2/data/www:/var/www/html
    - ./grow-m2-copy2/data/mysql:/var/lib/mysql
    - ./grow-m2-copy2/config/apache2:/etc/apache2
    container_name: grow-m2-copy2
  template-m2-copy:
    image: magestore/omnichannel_m2
    expose:
    - '80'
    - '443'
    volumes:
    - ./template-m2-copy/data/www:/var/www/html
    - ./template-m2-copy/data/mysql:/var/lib/mysql
    - ./template-m2-copy/config/apache2:/etc/apache2
    container_name: template-m2-copy
  grow-m2-from-template:
    image: magestore/omnichannel_m2
    expose:
    - '80'
    - '443'
    volumes:
    - ./grow-m2-from-template/data/www:/var/www/html
    - ./grow-m2-from-template/data/mysql:/var/lib/mysql
    - ./grow-m2-from-template/config/apache2:/etc/apache2
    container_name: grow-m2-from-template
